"""init_mysql_schema

Revision ID: 8e6521a2f978
Revises: 
Create Date: 2026-02-14 21:57:00.895869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8e6521a2f978'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_chat_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_full_input', sa.Text(), nullable=True),
    sa.Column('ai_reply_content', sa.Text(), nullable=True),
    sa.Column('ai_risk_flag', sa.Boolean(), nullable=True),
    sa.Column('ai_sentiment_score', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_chat_logs_id'), 'ai_chat_logs', ['id'], unique=False)
    op.create_index(op.f('ix_ai_chat_logs_session_id'), 'ai_chat_logs', ['session_id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('turn_1_answer', sa.Text(), nullable=True),
    sa.Column('turn_2_answer', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_chat_sessions_session_id'), 'chat_sessions', ['session_id'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_uid', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('poem_content', sa.Text(), nullable=True),
    sa.Column('image_style', sa.String(length=50), nullable=True),
    sa.Column('user_diary_summary', sa.Text(), nullable=True),
    sa.Column('island_category', sa.String(length=50), nullable=True),
    sa.Column('selected_tags', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=True),
    sa.Column('is_printed_intent', sa.Boolean(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('hug_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('reroll_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickets_id'), 'tickets', ['id'], unique=False)
    op.create_index(op.f('ix_tickets_ticket_uid'), 'tickets', ['ticket_uid'], unique=True)
    op.alter_column('tracking_events', 'event_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.create_index(op.f('ix_tracking_events_event_name'), 'tracking_events', ['event_name'], unique=False)
    op.alter_column('users', 'wechat_openid',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('users', 'avatar_url',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=512),
               existing_nullable=True)
    op.alter_column('users', 'ui_style_pref',
               existing_type=mysql.VARCHAR(length=32),
               type_=sa.String(length=20),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'ui_style_pref',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=32),
               existing_nullable=True)
    op.alter_column('users', 'avatar_url',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('users', 'wechat_openid',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_tracking_events_event_name'), table_name='tracking_events')
    op.alter_column('tracking_events', 'event_name',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_tickets_ticket_uid'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_id'), table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_chat_sessions_session_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_ai_chat_logs_session_id'), table_name='ai_chat_logs')
    op.drop_index(op.f('ix_ai_chat_logs_id'), table_name='ai_chat_logs')
    op.drop_table('ai_chat_logs')
    # ### end Alembic commands ###
